{% set name = "huxt" %}
{% set version = "5.0.2" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/huxt-{{ version }}.tar.gz
  sha256: 9a8b9ff2756e69c09332b167acc969ef92422c584b5fe7cc353896d3c21ca057

build:
  entry_points:
    - huxt-make-ephemeris = huxt.scripts.make_ephemeris:main
    - huxt-open-examples = huxt.scripts.open_examples_notebook:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12.11
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - appdirs >=1.4.4
    - astropy-base >=7.1.0
    - dtaidistance >=2.3.13
    - h5py >=3.14.0
    - httplib2 >=0.30.0
    - imageio >=2.37.0
    - imageio-ffmpeg >=0.6.0
    - jupyterlab >=4.4.7
    - matplotlib-base >=3.10.6
    - netcdf4 >=1.6.2
    - numba >=0.61.2
    - numpy >=2.2.6
    - pandas >=2.3.2
    - pytest >=8.4.2
    - requests >=2.32.5
    - scipy >=1.16.1
    - sunpy >=7.0.1
    - tqdm >=4.67.1

test:
  imports:
    - huxt
  source_files:
    - tests/
  commands:
    - pytest tests
  requires:
    - python {{ python_min }}
    - pytest

about:
  home: https://github.com/University-of-Reading-Space-Science/HUXt
  summary: Heliospheric Upwind eXtrapolation with Time-dependence. A computationally efficient solar wind model.
  description: |
    HUXt is a python implelementation of a computationally efficient solar wind model.
  license: MIT
  license_file: LICENSE.md
extra:
  recipe-maintainers:
    - LukeBarnard
